---
application:
  hmac_secret: super-long-and-secret-random-key-needed-to-verify-message-integrity
  port: 8241
database:
  database_name: newsletter
  host: localhost
  password: password
  port: 5432
  username: postgres
email_client:
  authorization_token: secret-token
  base_url: localhost
  sender_email: test@gmail.com
  timeout_milliseconds: 10000
redis_uri: redis://127.0.0.1:6379